services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - '3200:3200' # Tempo UI/API
      # 내부에서만 접근, 포트 바인딩 제거
    expose:
      - '4317' # 다른 컨테이너가 접근 가능하게 expose만

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.93.0
    container_name: otel_collector
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '4318:4318' # OTLP HTTP
      - '4317:4317' # OTLP gRPC

  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - tempo

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot-simulator
    ports:
      - '8000:8000'
    depends_on:
      - mqtt
      - otel-collector
    volumes:
      - ./config/config.toml:/app/config/config.toml
      - ./config/logger.toml:/app/config/logger.toml
    command: >
      simulator
      --config /app/config/config.toml
      --log-config /app/config/logger.toml
