[mqtt]
host = "localhost"
port = 1883
topic = "sensors/#"
qos = 0

[subscriber]
batch_size = 1000
min_batch_size = 500
max_batch_size = 10000
flush_interval = 3
mqtt_reconn_delay_sec = 5
error_retry_delay_sec = 5

[observability]
trace_endpoint = "http://localhost:4318/v1/traces"
service_name = "iot-subscriber"
prometheus_port = 8001

[redis]
host = "localhost"
port = 6379
stream_name = "sensor_data_stream"
maxlen = 100000  # 원하는 메시지 최대 개수