[mqtt]
host = "localhost"
port = 1883
topic = "sensors/#"
qos = 0

[database]
name = "iot_ml_lab"
user = "lab_admin"
password = "changeme"
host = "localhost"
port = 5432

[subscriber]
batch_size = 500
flush_interval = 5
mqtt_reconn_delay_sec = 5
error_retry_delay_sec = 5

[observability]
trace_endpoint = "http://localhost:4318/v1/traces"
service_name = "iot-subscriber"
prometheus_port = 8001
