[redis]
consumer = "redis-to-postgres"
group    = "sensor_group"
host     = "localhost"
port     = 6379
stream   = "sensor_data_stream"
ttl      = 3600

[postgres]
database        = "iot_ml_lab"
host            = "localhost"
max_retries     = 3
password        = "changeme"
pool_max_size   = 5
pool_min_size   = 1
port            = 5432
retry_delay_sec = 1
user            = "lab_admin"

[observability]
prometheus_port = 8011
service_name    = "redis-to-postgres"
trace_endpoint  = "http://localhost:4318/v1/traces"

[worker]
batch_size      = 100
block_ms        = 1000
retry_delay_sec = 2
