[redis]
host = "redis"
port = 6379
stream = "sensor_data_stream"
group = "sensor_group"
consumers = ["worker-1", "worker-2"]
ttl = 3600

[postgres]
host = "postgres"
port = 5432
database = "iot_ml_lab"
user = "lab_admin"
password = "changeme"
pool_min_size = 1
pool_max_size = 5
max_retries = 3
retry_delay_sec = 1

[observability]
service_name = "redis-to-postgres"
trace_endpoint = "http://otel-collector:4318/v1/traces"
prometheus_port = 8011

[worker.worker-1]
name = "worker-1"
batch_size = 3000
block_ms = 1000
retry_delay_sec = 2

[worker.worker-2]
name = "worker-2"
batch_size = 3000
block_ms = 1000
retry_delay_sec = 2

[worker.worker-1.observability]
service_name = "redis-to-postgres.worker-1"
trace_endpoint = "http://otel-collector:4318/v1/traces"
prometheus_port = 8012

[worker.worker-2.observability]
service_name = "redis-to-postgres.worker-2"
trace_endpoint = "http://otel-collector:4318/v1/traces"
prometheus_port = 8013