name: CI for Common Package (PR-based)

on:
  pull_request:
    branches:
      - main
    paths:
      - "python/common/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/common
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv .venv --python $(which python)

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: uv build --wheel

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-common
          path: python/common/dist/

  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/common
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-common
          path: python/common/dist/

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv .venv --python $(which python)

      - name: Install built wheel package
        run: uv pip install dist/*.whl

      - name: Install dev dependencies
        run: uv sync --group dev

      - name: Run tests
        run: uv run --active pytest
