name: Lint GitHub Workflows

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install actionlint
        run: |
          curl -sfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
          sudo mv actionlint /usr/local/bin/

      - name: Lint GitHub Workflows
        run: actionlint
