name: Release common Python package to GitHub Packages

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "common/**"
      - ".github/workflows/release-common.yaml"

  pull_request:
    paths:
      - "common/**"
      - ".github/workflows/release-common.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: common
    steps:
      - uses: actions/checkout@v4

      - name: Extract Python version from pyproject.toml
        id: extract-python
        run: |
          PYTHON_SPEC=$(grep -E '^[[:space:]]*python[[:space:]]*=' pyproject.toml | sed -E 's/.*=["'\''](.*)["'\'']/\1/')
          PYTHON_VERSION=$(echo "$PYTHON_SPEC" | grep -oE '[0-9]+\.[0-9]+' | head -n1)
          echo "version=$PYTHON_VERSION" >> "$GITHUB_OUTPUT"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.extract-python.outputs.version }}

      - name: Install Poetry from .poetry-version
        run: |
          pip install "poetry==$(cat .poetry-version)"

      - name: Show Poetry version
        run: poetry --version

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run pytest

      - name: Build package
        run: poetry build

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: common
    steps:
      - uses: actions/checkout@v4

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install Poetry from .poetry-version
        run: |
          pip install "poetry==$(cat .poetry-version)"

      - name: Publish to GitHub Packages
        env:
          POETRY_HTTP_BASIC_GITHUB__USERNAME: ${{ github.actor }}
          POETRY_HTTP_BASIC_GITHUB__PASSWORD: ${{ secrets.GH_WORKFLOW_TOKEN }}
        run: |
          poetry config repositories.github https://pypi.pkg.github.com/${{ github.repository_owner }}
          poetry publish -r github --no-interaction --username ${{ github.actor }} --password ${{ secrets.GH_WORKFLOW_TOKEN }} -C dist
