name: Release Python Common Package

on:
  push:
    tags:
      - "common-v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/common
    steps:
      - uses: actions/checkout@v4

      - name: Ensure tag is on main branch
        run: |
          git fetch origin main
          if ! git merge-base --is-ancestor origin/main $GITHUB_SHA; then
            echo "::error ::Tag must point to a commit that is on 'main' branch."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv .venv --python "$(which python)"

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: uv build --wheel

      - name: Publish to self-hosted devpi
        env:
          DEVPI_USER: seungbae
          DEVPI_PASSWORD: ${{ secrets.DEVPI_PASSWORD }}
        run: |
          uv publish --repository-url https://devpi.gitops.mrml.xyz/seungbae/dev \
                    -u $DEVPI_USER -p $DEVPI_PASSWORD dist/
