[mqtt]
host  = "mqtt"         # MQTT 브로커 주소 (로컬 혹은 Mosquitto 서비스명)
port  = 1883           # MQTT 브로커 포트
qos   = 1              # MQTT QoS 레벨 (0: at most once, 1: at least once, 2: exactly once)
topic = "sensors/data" # 메시지를 publish 할 토픽 이름

[simulation]
frequency_sec = 1     # 센서 데이터 전송 주기 (초 단위)
max_devices   = 10000 # 최대 시뮬레이션 장치 수

[server]
host = "0.0.0.0"
port = 8000

[observability]
prometheus_port = 8001
service_name    = "iot-simulator"
trace_endpoint  = "http://otel-collector:4318/v1/traces"
