disable_existing_loggers = true
version                  = 1

# =========================
# Formatters
# =========================

[formatters.json]
class = "iot_simulator.JSONFormatter"
# timestamp 포맷은 Formatter 클래스 내부에서 정의됨

# =========================
# Handlers
# =========================

[handlers.console]
class     = "logging.StreamHandler"
formatter = "json"
level     = "DEBUG"
stream    = "ext://sys.stdout"

[handlers.file]
backupCount = 5
class       = "logging.handlers.RotatingFileHandler"
encoding    = "utf-8"
filename    = "./tmp/simulator.log"
formatter   = "json"
level       = "INFO"
maxBytes    = 10485760                               # 10MB

# =========================
# Loggers
# =========================

[loggers."uvicorn"]
handlers  = ["console"]
level     = "INFO"
propagate = false

[loggers."uvicorn.error"]
handlers  = ["console"]
level     = "INFO"
propagate = false

[loggers."uvicorn.access"]
handlers  = ["console"]
level     = "INFO"
propagate = false

[loggers.simulator]
handlers  = ["console", "file"]
level     = "INFO"
propagate = false

[root]
handlers = ["console"]
level    = "INFO"
